version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tutorial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13i74oqm0zbz1"
s3_prefix = "tutorial"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["SNSFunction=424432388155.dkr.ecr.us-east-1.amazonaws.com/sns"]
