version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ping"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rm1qe0x5hh63"
s3_prefix = "ping"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["PingdFunction=424432388155.dkr.ecr.us-east-1.amazonaws.com/ping"]
