version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13i74oqm0zbz1"
s3_prefix = "api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
