version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "service-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rm1qe0x5hh63"
s3_prefix = "service-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=424432388155.dkr.ecr.us-east-1.amazonaws.com/service-1"]
